### ISSUE TITLE
No Folds Found

### ISSUE THREAD

**Issue by erikc96** [axvr/org.vim#2]
Hi,

As the title suggests, I'm getting an error when trying to fold a heading that suggests that folds aren't working.

Syntax highlighting is working, and the plugin shows up in :scriptnames.

Here's an example file I'm using.

~~~
#+TITLE:     Emacs org-mode examples
#+AUTHOR:    Eric H. Neilsen, Jr.
#+EMAIL:     neilsen@fnal.gov

* TODO vim org mode

~~~

**Comment by axvr** [comment]
I managed to find your vimrc from [a comment you left on another plugin's issue tracker](https://github.com/jceb/vim-orgmode/issues/361#issue-683762488) and I think I've found the problem for both.  In your vimrc you'll need to change the line:

```vim
filetype on
```

to 

```vim
filetype plugin indent on
```

Otherwise Vim won't load some of the files of the plugins you have installed.

**Comment by erikc96** [comment]
Wow, you really got me on that one. Thank you so much! Made my day, I've
been dying to have access to org mode!
