### ISSUE TITLE
TAB not working

### ISSUE THREAD

**Issue by ghost** [axvr/org.vim#5]
Hi there. I just installed neovim and org.vim, syntax highlighting of org files and folding (manually using z commands) work perfectly. But when pressing tab nothing happens (and no errors). I expected the folding to cycle like emacs.

my ~/.config/nvim/init.vim:

```
call plug#begin(stdpath('data') . '/plugged')
Plug 'axvr/org.vim'
call plug#end()
```
also :set foldexpr foldtext foldmethod
```
  foldexpr=org#fold_expr()
  foldtext=foldtext()
  foldmethod=expr
```

**Comment by axvr** [comment]
Org.vim doesn't define any key bindings of it's own, it's designed to only use the standard Vim features and key bindings.  If you want a more full-featured Org mode plugin for Vim, then I recommend [Vim-orgmode](https://github.com/jceb/vim-orgmode) instead of Org.vim.

However if you do want this behaviour in Org.vim, I've created an extension which you can add to your Neovim config:

https://gist.github.com/axvr/19dc08a63d9772df5748d557bc52ec76

Simply download the file and move it to `~/.config/nvim/after/ftplugin/org.vim`.  This extension will add the Tab and Shift-Tab key bindings you are used to in Emacs, it's not exactly the same but it's very close.

_(Note that one of the states for Shift-Tab ("CONTENTS") isn't possible in Vim without a lot more code, so I didn't add it.)_

I hope this helps.

**Comment by ghost** [comment]
works perfectly, thank you!
